### PR TITLE
Remove version from install path

### PR DESCRIPTION
**Pull request by jfalcou**

### CODE REVIEW

**Comment by jfalcou** [comment]
@JPenuchot if you want to try this branch and tell me if it is OK for your use case :)

**Review by DenisYaroshevskiy — APPROVED** [review]
Blind approve

**Comment by JPenuchot** [comment]
I'll take a look at it during the week, thanks!

**Review by JPenuchot — APPROVED** [review]
File list looks good to me: [filelist.txt](https://github.com/jfalcou/eve/files/12586525/filelist.txt)

**Pull request merged**
