### PR TITLE
Update external dependies management

### PR DESCRIPTION
**Pull request by jfalcou**

### CODE REVIEW

**Comment by DenisYaroshevskiy** [comment]
Is this just moving files?

**Comment by jfalcou** [comment]
Nah, if you look at the end of the detail file, you'll find the `__has_include` thing we discussed

```c++
#define KUMI_NO_STD_ADAPTORS
#if __has_include(<kumi/tuple.hpp>)
# include <kumi/tuple.hpp>
#else
# if defined(EVE_USE_EXTERNAL_DEPENDENCIES)
#   error "[EVE] External KUMI dependencies requested but none is available"
#   include <kumi/tuple.hpp>
# else
#   include <eve/deps/kumi/tuple.hpp>
# endif
```

**Comment by DenisYaroshevskiy** [comment]
Figure out some ci for external deps and I'll stump this. 
Noting here too that the necessity to use NO_STD_ADAPTORS will cause odr violations.

**Comment by jfalcou** [comment]
> Noting here too that the necessity to use NO_STD_ADAPTORS will cause odr violations.
I propose we remove it later by fixing the actual EVE code that is now ambiguous in a later PR

**Review by DenisYaroshevskiy — APPROVED** [review]

**Pull request merged**
