### PR TITLE
Transparent types support in eve::wide

### PR DESCRIPTION
**Pull request by SadiinsoSnowfall**
TODO:

- [ ] what to do with eq/neq operators
- [ ] what to do with the other operators

### CODE REVIEW

**Comment by DenisYaroshevskiy** [comment]
I think this needs a discussion before doing anything. 
enums are not special, char, uintptr_t or smth like that is similar.
+ needs to handle so that the amount of work required on the changes is minial - so probably callable should do smart things.

**Comment by jfalcou** [comment]
> I think this needs a discussion before doing anything. enums are not special, char, uintptr_t or smth like that is similar.
> 
> * needs to handle so that the amount of work required on the changes is minial - so probably callable should do smart things.

This preliminary work is mostly so that `wide<ENUM>` works in term of basic functionality. @SadiinsoSnowfall put soemthign in place that minimizes the amoutn of touch up in non common files and arch specific ones. The question we have is that we can't have any function works on any enum cause MAYBE for the user it make no sense.

So the plan of this draft is to explore what we should do, startign with basic features. We can chat about what we should be doing further in a call.

**Comment by DenisYaroshevskiy** [comment]
Well, for example, existance of logical<wide<enum>> is not obvious to me. 
There is no logicals for bundles, for example.

Also - I am pretty sure f16 won't work if you try to use the same mechanism as enum.
I would like some design doc or at lesat ideas outline - otherwise I believe we will rush into something that we don't fully understand.

**Comment by jfalcou** [comment]
> Well, for example, existance of logical<wide> is not obvious to me. There is no logicals for bundles, for example.
> 
> Also - I am pretty sure f16 won't work if you try to use the same mechanism as enum. I would like some design doc or at lesat ideas outline - otherwise I believe we will rush into something that we don't fully understand.
> 
> UPD: if you just want to prototype to see what's up - no problem. But please - discussion before you publish this pr as pr.


Yup sure, this draft is there so @SadiinsoSnowfall  can see the CI and how it reacts.
We need a call.

**Comment by DenisYaroshevskiy** [comment]
A post or a call - just some ideas/goals.

**Comment by DenisYaroshevskiy** [comment]
Hi.

I think this pull request is growing a lot. It is preferable to not put one big patch all at once. Do you think you can split?

**Comment by DenisYaroshevskiy** [comment]
There is 36 files changed and you are still working. It doesn't have to work all or nothing. You can do a bit

**Pull request closed without merging**
